language: android

jdk:
  - oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-28.0.3
    - $ANDROID_TARGET
    - sys-img-$ANDROID_ABI-$ANDROID_TARGET

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools
  - sdkmanager --list
  # Install the system image
  - sdkmanager "system-images;$ANDROID_TARGET;google_apis;$ANDROID_ABI"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;$ANDROID_TARGET;default;$ANDROID_ABI"
  - emulator -avd test -no-audio -no-window &

install: ./gradlew clean assemble assembleAndroidTest --stacktrace

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew check connectedCheck --stacktrace
