
name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          # TODO: Multiple Java versions
          java-version: 1.8
      - name: Build # Including tests
        run: ./gradlew clean build --stacktrace
